kind = "Article"
version = 1
content = '''
Simplicity is Ultimate Sophistication. [Credit](https://quoteinvestigator.com/2015/04/02/simple/)

How I was convinced to truly appreciate simplicity.

<!-- more -->

<video
  controls
  preload="metadata"
  onloadstart="this.volume=0.4"
  onloadedmetadata="this.currentTime=4"
  style="width: 100%; max-width:100 margin: 0 auto; text-align: center;">
  <source src="/assets/videos/rich-hickey_simple-made-easy_2011.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>
'''

[metadata]
title = "Ultimate Sophistication is Simplicity"
description = "Simplicity is Ultimate Sophistication."
date = "20250819T203923+02:00"

[metadata.extra]
toc = false

[metadata.taxonomies]
categories = ["philosophy"]
tags = [
    "dev",
    "dev/software/design",
    "dev/software/architecture",
    "dev/programming/functional",
]