name: Zola on GitHub Pages

on:
 push:
  branches:
   - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
    - name: Build and deploy
      # https://github.com/shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.21.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
